/// Registre des contrôles qualité réalisés sur les trois bases (une ligne par contrôle).
table 'Contrôles qualité'

	/// Nombre de contrôles qualité.
	measure 'Contrôles réalisés' = COUNTROWS('Contrôles qualité')
		formatString: #,##0
		displayFolder: Qualité

	/// Contrôles dont l'anomalie invalide l'usage d'un indicateur.
	measure 'Contrôles critiques' = CALCULATE([Contrôles réalisés], 'Contrôles qualité'[Gravité] = "Critique")
		formatString: #,##0
		displayFolder: Qualité

	/// Contrôles de gravité élevée.
	measure 'Contrôles gravité élevée' = CALCULATE([Contrôles réalisés], 'Contrôles qualité'[Gravité] = "Élevée")
		formatString: #,##0
		displayFolder: Qualité

	/// Taux moyen de lignes en anomalie (par contrôle).
	measure 'Taux anomalie' = AVERAGE('Contrôles qualité'[Taux])
		formatString: 0.0%
		displayFolder: Qualité

	/// Numéro du contrôle.
	column 'ID contrôle'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ID

	/// Base contrôlée.
	column Base
		dataType: string
		summarizeBy: none
		sourceColumn: Source

	/// Dimension qualité : Complétude, Unicité, Cohérence, Validité, Représentativité.
	column Dimension
		dataType: string
		summarizeBy: none
		sourceColumn: Dimension

	/// Description du contrôle.
	column 'Contrôle'
		dataType: string
		summarizeBy: none
		sourceColumn: Controle

	/// Nombre de lignes concernées.
	column 'Lignes en anomalie'
		dataType: int64
		formatString: #,##0
		summarizeBy: sum
		sourceColumn: Nb_Anomalies

	/// Nombre de lignes contrôlées.
	column 'Lignes contrôlées'
		dataType: int64
		formatString: #,##0
		summarizeBy: sum
		sourceColumn: Nb_Total

	/// Lignes en anomalie / lignes contrôlées.
	column Taux
		dataType: decimal
		isHidden
		summarizeBy: none
		sourceColumn: Taux

	/// Critique, Élevée, Moyenne, Faible.
	column 'Gravité'
		dataType: string
		summarizeBy: none
		sourceColumn: Gravite
		sortByColumn: 'Ordre gravité'

	/// Impact et recommandation.
	column Commentaire
		dataType: string
		summarizeBy: none
		sourceColumn: Commentaire

	/// Ordre de tri de la gravité.
	column 'Ordre gravité'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: Ordre gravité

	partition 'Contrôles qualité' = m
		mode: import
		source =
				let
				    // Lecture du fichier CSV nettoyé produit par l'analyse
				    #"Fichier lu" = Csv.Document(File.Contents(DossierDonnees & "qualite_controles.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"En-têtes promus" = Table.PromoteHeaders(#"Fichier lu", [PromoteAllScalars = true]),
				    #"Colonnes retenues" = Table.SelectColumns(#"En-têtes promus", {"ID", "Source", "Dimension", "Controle", "Nb_Anomalies", "Nb_Total", "Taux", "Gravite", "Commentaire"}),
				    #"Types appliqués" = Table.TransformColumnTypes(#"Colonnes retenues", {{"ID", Int64.Type}, {"Source", type text}, {"Dimension", type text}, {"Controle", type text}, {"Nb_Anomalies", Int64.Type}, {"Nb_Total", Int64.Type}, {"Taux", Currency.Type}, {"Gravite", type text}, {"Commentaire", type text}}, "en-US"),
				    #"Ordre gravité ajouté" = Table.AddColumn(#"Types appliqués", "Ordre gravité", each if [Gravite] = "Critique" then 1 else if [Gravite] = "Élevée" then 2 else if [Gravite] = "Moyenne" then 3 else 4, Int64.Type)
				in
				    #"Ordre gravité ajouté"

